name: APP_NAME
namespace: APP_NAME
replicas: 1

image:
  url: IMAGE_URL
  pullPolicy: Always

config:
  profile: PROFILE
  executablePath: EXECUTABLE_PATH
  #####################
  ## The configmap is created from file which is prepared
  ## by 'serve-java-app'  workflow.
  ## By default, it's mounted into `/config/application.yml`,
  ## which can be used as default config or additional config.
  configmap_enabled: CONFIGMAP_ENABLED
  #####################
  ## The secret is created from file which is prepared
  ## by 'serve-java-app'  workflow.
  ## By default, it's mounted into `/secret/secret_data`.
  secret_enabled: SECRET_ENABLED

extraEnv: {}
  ## Extra environment variables to be injected
  # SPRING_CONFIG_LOCATION: file:/config/application.yml
  # SPRING_CONFIG_ADDITIONAL_LOCATION: file:/config/application.yml
  # ...


podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: PORT_NUM
  metricsPort: 9464

ingress:
  enabled: false
#  annotations: {}
#  hosts:
#    - host: chart-example.local
#      paths: []
#  tls: []
#    - secretName: chart-example-tls
#      hosts:
#        - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources: {}

canary:
  enabled: false
  successThreshold: 95

persistence:
  enabled: PV_ENABLED
  storageClass: PV_STORAGE_CLASS
  accessMode: PV_ACCESS_MODE
  size: PV_SIZE
  mountPath: PV_MOUNT_PATH
