---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: lma
spec:
  namespaceSelector:
    matchNames:
    - petclinic
  selector:
    matchLabels:
      app: petclinic
  podMetricsEndpoints:
  - targetPort: 9464
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: petclinic-primary
  name: petclinic-primary
  namespace: lma
spec:
  namespaceSelector:
    matchNames:
    - petclinic
  selector:
    matchLabels:
      app: petclinic-primary
  podMetricsEndpoints:
  - targetPort: 9464
