{{- if .Values.canary.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.lmaNamespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  podMetricsEndpoints:
  - targetPort: 9464
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: {{ .Values.name }}-primary
  name: {{ .Values.name }}-primary
  namespace: {{ .Values.lmaNamespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-primary
  podMetricsEndpoints:
  - targetPort: 9464
{{- end }}
