{{- if .Values.config.secret_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  secret_data: {{ tpl (.Files.Get "secret_data") . | b64enc }}
{{- end }}
