{{- if .Values.config.secret_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  secret_content: |
{{ .Files.Get "secret_content" | b64enc | indent 4  }}
{{- end }}
