{{- if (hasKey .Values.config "secretContent") }}
apiVersion: v1
kind: Secret
metadata:
  name: name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app:
type: Opaque
data:
  ## TODO: how is this mounted to specific file?
  data: {{ .Values.config.secretContent | b64enc | quote }}
{{- end }}
