apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: web
	  port: {{ .Values.service.port }}
		targetPort: {{ .Values.service.port }}
		protocol: TCP
  selector:
    app: {{ .Values.name }}
