---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APPNAME
  name: APPNAME
spec:
  template:
    spec:
      containers:
      - image: IMAGEURL
        name: APPNAME
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
          limits:
            memory: "4Gi"
            cpu: "4"
