---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APPNAME
  name: APPNAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      containers:
      - image: IMAGEURL
        name: APPNAME
        resources: {}
        command:
        - java
        - -Dspring.profiles.active=PROFILE
        - -XX:MinRAMPercentage=50.0
        - -XX:MaxRAMPercentage=75.0
        - -XshowSettings:vm
        - -jar
        - EXECUTABLE_PATH
        ports:
        - containerPort: PORTNUM
status: {}
